### PR TITLE
to_json now can get options

### PR DESCRIPTION
**Pull request by duncanita**
I'm using tthe gem without active support and i get this error

ArgumentError: wrong number of arguments (1 for 0)
from /home/duncan/.rvm/gems/ruby-2.2.3/gems/powertrack-1.0.1/lib/powertrack/rules/rule.rb:65:in `to_json'

### CODE REVIEW

**Comment by lfarcy** [comment]
Hi Riccardo,

Great to here you're using the gem. I really hope it's useful and works adequately.

What's the deal with ActiveSupport ? It's true we only use this gem in a Rails app where ActiveSupport is automatically loaded. But I don't understand why to_json has to take options to make it work w/o ActiveSupport loaded...

Do you have some clues ?

**Comment by lfarcy** [comment]
Looking at the unit test, I can see that the to_json method successfully runs w/o ActiveSupport. Is there something specific to your environment ?

**Comment by duncanita** [comment]
Hi Laurent, is a problem with patched hash from activesupport and MultiJson.encode

With standard json adapter the :encode method call :dump of JsonCommon, you can find it here

https://github.com/intridea/multi_json/blob/master/lib/multi_json/adapters/json_common.rb#L19

**Comment by lfarcy** [comment]
If I understand well, the issue appears when the gem is used together with ActiveSupport. This is the opposite of what you initially claimed when you submitted the push request...

I'm still confused about the exact circumstances when the issue happens. Can you provide me with an example of code ? As such, it does not look like an issue of the powertrack gem but more as an issue of the JsonCommon adapter...

**Comment by duncanita** [comment]
Sorry, should be my English :)

I link a gist

https://gist.github.com/duncanita/fd470c5667185c018d85

**Comment by lfarcy** [comment]
Thanks for the gist. It's perfectly clear now.

After reviewing the rdoc, I understand the json standard library defines the to_json method with some optional arguments. Weird...

Consequently, for the powertrack gem to support this library (through the MultiJson gem), we must add some optional arguments to Rule.to_json.

Before merging your PR, I'd like to know if
1. The unit tests continue to pass on your side
2. The options received by Rule.to_json should be passed to MultiJson.encode ?

Best

**Comment by lfarcy** [comment]
Riccardo,

Any news on your side ?

Thx.

**Comment by duncanita** [comment]
Hi, sorry for the delay
1. I have tried the test and still pass
2. I think yes, but in our scenario is not necessary

tnx

**Comment by lfarcy** [comment]
Can you please update the PR to pass the options to MultiJson.encode ? 

See https://github.com/intridea/multi_json/blob/master/lib/multi_json.rb#L135-L138

Once you do that, I'll merge the PR into the trunk.

**Comment by duncanita** [comment]
Hi, thank you :)

**Pull request merged**
